---
- hosts: rsyslog
  become: yes
  tasks:
  - name: install rsyslog
    ansible.builtin.dnf:
      name: rsyslog
      state: present
    notify:
      - rsyslog server config
      - enable rsyslog
      
  handlers:
  
  - name: rsyslog server config
    replace:
      path: /etc/rsyslog.conf
      regexp: "{{ item }}"
      replace: "\\1"
    loop:
      - '#(module\(load=”imudp”\))'
      - '#(input\(type=”imudp” port=”514”\))'
      - '#(module\(load=”imtcp”\))'
      - '#(input\(type=”imtcp” port=”514”\))'
    notify:
      - start rsyslog
     
  - name: enable rsyslog
    ansible.builtin.systemd:
      name: rsyslog
      enabled: yes
      
  - name: start rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: started
...