---
- name: web server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
    notify:
      - enable nginx
      - start nginx
  
  handlers:

  - name: enable nginx
    ansible.builtin.systemd:
      name: nginx
      enabled: yes

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
...