---
- hosts: all
  become: true
  tasks:

  - name: ru locale
    ansible.builtin.dnf:
      name: glibc-langpack-ru
      state: latest

  - name: set timezone to Moscow
    timezone:
      #name: Asia/Tokyo
      name: Europe/Moscow

  - name: restart chronyd
    ansible.builtin.service:
      name: chronyd
      state: restarted

  - name: get time for print
    shell: "date"
    register: tstamp

  - name: print time
    debug:
      msg: "текущее время на сервере {{ tstamp.stdout }}"

  - name: Install Vim
    ansible.builtin.dnf:
      name: vim
      state: latest

- hosts: webmachine
  become: true
  gather_facts: no
  tasks:

  - name: install nginx > 1.7
    ansible.builtin.dnf:
      name: nginx > 1.7
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started

  - name: enable nginx
    ansible.builtin.systemd:
      name: nginx
      enabled: yes

  - name: copy nginx config
    copy:
      src: ./webmachine_nginx.conf
      dest: /etc/nginx/nginx.conf
      remote_src: no
      mode: 0644
      owner: root
      group: root
    notify:
      - restart nginx

  handlers:

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted


- hosts: logmachine
  become: true
  gather_facts: no
  tasks:

  - name: started rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: started

  - name: copy rsyslog config
    copy:
      src: ./logmachine_rsyslog.conf
      dest: /etc/rsyslog.conf
      remote_src: no
      mode: 0644
      owner: root
      group: root
    notify:
      - restart rsyslog

  handlers:

  - name: restart rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: restarted
    
...
