---
- hosts: all
  become: true
  tasks:
  - name: Set timezone to Moscow
    timezone:
      #name: Asia/Tokyo
      name: Europe/Moscow

  - name: Restart chronyd
    ansible.builtin.service:
      name: chronyd
      state: restarted

  - name: Get time for print
    shell: "date"
    register: tstamp

  - name: Print time
    debug:
      msg: "Текущее время на сервере {{ tstamp.stdout }}"

  - name: Install Vim
    ansible.builtin.dnf:
      name: vim
      state: latest

- hosts: webmachine
  become: true
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

...
