- name: install ru locale
  ansible.builtin.dnf:
    name: glibc-langpack-ru
    state: present

- name: set timezone to Moscow
  timezone:
    #name: Asia/Tokyo
    name: Europe/Moscow
  notify:
    - restart chronyd

- name: Install Vim
  ansible.builtin.dnf:
    name: vim
    state: present
