- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes

- name: restart auditd
  ansible.builtin.command: "service auditd restart"