- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  notify:
    - start nginx
    - enable nginx

- name: copy nginx config
  copy:
    src: ./roles/nginx/files/nginx.conf
    dest: /etc/nginx/nginx.conf
    remote_src: no
    mode: 0644
    owner: root
    group: root
  notify:
    - restart nginx


- name: copy auditd rules
  copy:
    src: ./roles/nginx/files/nginx.rules
    dest: /etc/audit/rules.d/nginx.rules
    remote_src: no
    mode: 0644
    owner: root
    group: root
  notify:
    - restart auditd
